#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.mia
	set firewall.mia=include
	set firewall.mia.type=script
	set firewall.mia.path=/etc/mia.include
	set firewall.mia.reload=1
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mia[-1]
	add ucitrack mia
	set ucitrack.@mia[-1].init=mia
	commit ucitrack

EOF

rm -rf /tmp/luci-*cache
exit 0